image: nikolaik/python-nodejs:python3.7-nodejs12

before_script:
    - pip install imgyaso
    - npm install -g epub-crawler
    # pass in $CONFIG at the screen of new pipelines/schedules
    - echo $CONFIG > config.json

    
job:
  script:
    - crawl-epub config.json
  except:
    - pushes
    - merge_requests
    
after_script:
  - export TM=$(date "+%Y%m%d%H%M%S%3N")
  - mkdir out
  - mv *.epub out/
  - cd out
  - git init
  - git config user.name ${GL_UN}
  - git config user.email ${GL_EMAIL}
  - git add -A
  - git commit -am $TM
  # configure $GL_TOKEN in the project CI/CD setting
  # the generated epub is pushed to a branch named the current time
  - git push "https://oauth2:${GL_TOKEN}@gitlab.com/${GL_USER}/${GL_REPO}.git" master:${TM} -f


# configure these variables
variables:
  GL_UN: GL_UN # username of git commit
  GL_EMAIL: GL_EMAIL # email of git commit
  GL_USER: GL_USER # gitlab username
  GL_REPO: GL_REPO # gitlab repo name