image: nikolaik/python-nodejs:python3.7-nodejs12

before_script:
    - apt update -y
    - apt install -y libgl1
    - pip install imgyaso
    - npm install -g epub-crawler
    - echo $CONFIG > config.json
    - imgyaso -v

    
job:
  script:
    - crawl-epub config.json
  except:
    - pushes
    - merge_requests
    
after_script:
  - export TM=$(date "+%Y%m%d%H%M%S%3N")
  - mkdir out
  - mv *.epub out/
  - mv config.json out/
  - cd out
  - git init
  - git config user.name ${GL_UN}
  - git config user.email ${GL_EMAIL}
  - git add -A
  - git commit -am $TM
  - git push "https://oauth2:${GL_TOKEN}@gitlab.com/${GL_USER}/${GL_REPO}.git" master:${TM} -f

  
variables:
  GL_UN: wizardforcel
  GL_EMAIL: 562826179@qq.com
  GL_USER: wizardforcel
  GL_REPO: epub-crawl-ci
